apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-image-build-push
  namespace: demo
spec:
  type: image
  params:
  - name: url
    value: testing2016/demo:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-git-build-push
  namespace: demo
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/slfletch/tenant
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: git-resource-branch-
  namespace: demo
spec:
  taskSpec:
    inputs:
      resources:
      - name: tenant
        type: git
    steps:
    - image: ubuntu
      script: cat tenant/Dockerfile
  inputs:
    resources:
    - name: tenant
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/slfletch/tenant
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: demo
  name: build-and-push-task
spec:
  resources:
    inputs:
      - name: workspace
        type: git
  steps:
    - name: build-and-push-step
      image: gcr.io/kaniko-project/executor:v0.19.0
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      command:
        - /kaniko/executor
        - --dockerfile=/workspace/workspace/Dockerfile
        - --context=/workspace/workspace/
        - --destination=testing2016/demo:latest
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  namespace: demo
  name: build-and-push-taskrun
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-and-push-task
  resources:
    inputs:
      - name: workspace
        resourceRef:
          name: demo-git-build-push
