---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-pod-reader
  namespace: demo
rules:
- apiGroups: ["helm.fluxcd.io"] # "" indicates the core API group
  resources: ["helmreleases"]
  verbs: ["get","list","describe"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get","list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list","describe"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  resources:
  - configmaps
  verbs:
  - get
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-pod-reader
  namespace: harbor
rules:
- apiGroups: ["helm.fluxcd.io"] # "" indicates the core API group
  resources: ["helmreleases"]
  verbs: ["get","list","describe"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get","list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list","describe"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  resources:
  - configmaps
  verbs:
  - get
