kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-reader-binding
  namespace: demo
subjects:
# Kubernetes service account
- kind: ServiceAccount
  name: demo-svc
roleRef:
  kind: Role
  name: demo-pod-reader
  apiGroup: ""
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-reader-binding
  namespace: harbor
subjects:
# Kubernetes service account
- kind: ServiceAccount
  name: demo-svc
roleRef:
  kind: Role
  name: demo-pod-reader
  apiGroup: ""
---
  apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-open-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: demo-svc
    namespace: demo