apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: demo-task-run-scdi-valid-user
  namespace: demo-pipeline
spec:
  serviceAccountName: demo-pipeline-svc
  taskSpec:
    steps:
    - name: demo-setup-valid-user
      image: stacey-0.localdomain:30003/tcicd/demo:1.5
      script: |
        #!/bin/bash
        /usr/local/bin/setup.sh
    - name: demo-run-valid-user
      image: stacey-0.localdomain:30003/tcicd/demo:1.5
      script: |
        #!/bin/bash
        /usr/local/bin/run.sh
    - name: demo-test-valid-user
      image: stacey-0.localdomain:30003/tcicd/demo:1.5
      script: |
        #!/bin/bash
        /usr/local/bin/test.sh
